import {dateKey,parseDate,nextDate,clock,signature,makePeriods,replaceDay,describe} from './hours.js';
const $=id=>document.getElementById(id);
const apiBase='https://mybusinessbusinessinformation.googleapis.com/v1/';
let token='',expiresAt=0,locationName='',periods=[],loaded=false,busy=false,closed=false,pending=null,session=0;
const configKey='special-hours-oauth-client';
function notice(text,kind='info'){$('notice').textContent=text;$('notice').dataset.kind=kind;}
function controls(){const ready=!!token&&loaded&&!busy;$('save').disabled=!ready;$('delete').disabled=!ready||!periods.some(p=>dateKey(p.startDate)===$('date').value);$('refresh').disabled=!token||busy;$('connect').disabled=busy;$('disconnect').disabled=busy;$('disconnect').hidden=!token;$('connect').hidden=!!token;document.querySelectorAll('.editor input,.editor select,.editor button,.schedule-day,#save-config').forEach(el=>{if(!['save','delete'].includes(el.id))el.disabled=busy;});}
function reset(){session++;token='';expiresAt=0;locationName='';periods=[];loaded=false;$('connection').textContent='未接続';$('schedule-list').replaceChildren();const p=document.createElement('p');p.className='empty';p.textContent='接続後に表示されます。';$('schedule-list').append(p);loadDay();controls();}
async function request(url,options={}){if(!token||Date.now()>=expiresAt){reset();throw Error('接続の有効期限が切れました。Googleに再接続してください。');}const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const res=await fetch(url,{...options,signal:controller.signal,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...options.headers},cache:'no-store'});if(res.status===401){reset();throw Error('Googleに再接続してください。');}let data={};try{data=await res.json();}catch{}if(!res.ok){const hints={403:'管理権限、API有効化、OAuth同意設定を確認してください。',404:'対象のビジネスが見つかりません。',429:'APIの利用制限に達しました。少し待って再読み込みしてください。'};throw Error(`Google API (${res.status}): ${hints[res.status]||data.error?.message||'処理に失敗しました。再読み込みしてください。'}`);}return data;}catch(e){if(e.name==='AbortError')throw Error('通信がタイムアウトしました。再読み込みして反映状況を確認してください。');throw e;}finally{clearTimeout(timer);}}
async function discover(){const matches=[];let page='';do{const a=await request('https://mybusinessaccountmanagement.googleapis.com/v1/accounts?pageSize=20'+(page?'&pageToken='+encodeURIComponent(page):''));for(const account of a.accounts||[]){let lp='';do{const list=await request(apiBase+account.name+'/locations?readMask=name,title&pageSize=100'+(lp?'&pageToken='+encodeURIComponent(lp):''));for(const loc of list.locations||[])if(/Mea Tattoo Studio/i.test(loc.title||''))matches.push(loc);lp=list.nextPageToken||'';}while(lp);}page=a.nextPageToken||'';}while(page);const unique=[...new Map(matches.map(l=>[l.name,l])).values()];if(unique.length!==1)throw Error(unique.length?'同名の店舗が複数あります。接続するアカウントを確認してください。':'Mea Tattoo Studioを管理するGoogleアカウントで接続してください。');return unique[0];}
async function read(){return request(apiBase+locationName+'?readMask=name,title,specialHours,regularHours');}
function rowsForDay(){return periods.filter(p=>dateKey(p.startDate)===$('date').value);}
function mode(value){closed=value;$('open-day').setAttribute('aria-pressed',String(!closed));$('closed-day').setAttribute('aria-pressed',String(closed));$('intervals').hidden=closed;$('add-interval').hidden=closed;$('time-help').hidden=closed;}
function picker(label,value,options){const select=document.createElement('select');select.setAttribute('aria-label',label);for(const [v,text] of options){const opt=new Option(text,String(v));select.add(opt);}select.value=String(value);if(select.selectedIndex<0)select.selectedIndex=-1;return select;}
function addRow(period){const index=$('intervals').children.length+1;const row=document.createElement('div');row.className='interval';const head=document.createElement('div');head.className='interval-head';const title=document.createElement('span');title.textContent='時間帯 '+index;const remove=document.createElement('button');remove.textContent='除く';remove.setAttribute('aria-label','この時間帯を除く');remove.onclick=()=>{row.remove();controls();};head.append(title,remove);row.append(head);const times=document.createElement('div');times.className='time-row';for(const which of ['open','close']){const block=document.createElement('div');const label=document.createElement('label');label.textContent=which==='open'?'開始':'終了';block.append(label);const current=period?.[which+'Time']||{hours:which==='open'?11:20,minutes:0};const wrap=document.createElement('div');wrap.className='time-picker';const hour=picker(`${index} ${label.textContent} 時`,current.hours===24?0:current.hours||0,Array.from({length:24},(_,h)=>[h,`${h%12||12} ${h<12?'am':'pm'}`]));hour.className=which+'-hour';const minute=picker(`${index} ${label.textContent} 分`,current.minutes||0,[[0,'00'],[30,'30']]);minute.className=which+'-minute';if(minute.selectedIndex<0){minute.add(new Option('選択', '',true,true));}wrap.append(hour,document.createTextNode(':'),minute);block.append(wrap);if(which==='close'){const day=picker(`${index} 終了日`,period&&(period.closeTime?.hours===24||period.endDate&&dateKey(period.endDate)!==dateKey(period.startDate))?1:0,[[0,'当日'],[1,'翌日']]);day.className='end-day';block.append(day);}times.append(block);}row.append(times);$('intervals').append(row);controls();}
function loadDay(){const selected=rowsForDay();$('day-state').textContent=!loaded?'未読み込み':selected.length?'登録済み：'+selected.map(describe).join(' / '):'特別営業時間の登録なし';mode(selected.some(p=>p.closed));$('intervals').replaceChildren();const open=selected.filter(p=>!p.closed);if(open.length)open.forEach(addRow);else addRow();renderList();controls();}
function renderList(){if(!loaded)return;const groups=new Map();for(const p of periods){const d=dateKey(p.startDate);if(!groups.has(d))groups.set(d,[]);groups.get(d).push(p);}const list=$('schedule-list');list.replaceChildren();if(!groups.size){const p=document.createElement('p');p.className='empty';p.textContent='登録はありません。左の日付から追加できます。';list.append(p);}for(const [date,ps] of [...groups].sort(([a],[b])=>a.localeCompare(b))){const b=document.createElement('button');b.className='schedule-day';if(date===$('date').value)b.setAttribute('aria-current','date');const title=document.createElement('strong');title.textContent=displayDate(date);const times=document.createElement('span');times.textContent=ps.map(describe).join(' / ');b.append(title,times);b.onclick=()=>{$('date').value=date;loadDay();$('date').focus();};list.append(b);}}
function displayDate(date){const d=parseDate(date);return new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short',timeZone:'Asia/Tokyo'}).format(new Date(Date.UTC(d.year,d.month-1,d.day,3)))+` · ${d.year}`;}
async function refresh(){const generation=session;busy=true;controls();notice('Googleから読み込み中…');try{const data=await read();if(generation!==session)return;periods=data.specialHours?.specialHourPeriods||[];loaded=true;loadDay();notice('登録済みの特別営業時間を読み込みました。');}catch(e){notice(e.message,'error');}finally{busy=false;controls();}}
function draft(){const rows=[...$('intervals').children].map(row=>({openTime:{hours:Number(row.querySelector('.open-hour').value),minutes:Number(row.querySelector('.open-minute').value)},closeTime:{hours:Number(row.querySelector('.close-hour').value),minutes:Number(row.querySelector('.close-minute').value)},nextDay:row.querySelector('.end-day').value==='1'}));if(!closed&&[...document.querySelectorAll('#intervals select')].some(s=>s.value===''))throw Error('時刻の分は00または30を選んでください。');return makePeriods($('date').value,closed,rows);}
function confirmChange(remove){try{const date=$('date').value;parseDate(date);const replacements=remove?[]:draft();replaceDay(periods,date,replacements);pending={date,replacements,baseline:signature(periods)};$('confirm-title').textContent=remove?'特別営業時間を削除しますか？':'この内容で保存しますか？';$('confirm-text').textContent=displayDate(date)+'\n'+(remove?'通常営業時間に戻ります。':replacements.map(describe).join('\n'));$('confirm-dialog').showModal();}catch(e){notice(e.message,'error');}}
async function apply(){const change=pending;if(!change||busy||!loaded||!token)return;$('confirm-dialog').close();pending=null;busy=true;controls();notice('Googleに保存中…');try{const latest=await read();const current=latest.specialHours?.specialHourPeriods||[];if(signature(current)!==change.baseline){periods=current;loadDay();throw Error('別の画面で営業時間が変更されました。最新の登録を読み込んだので、内容を確認してもう一度保存してください。');}const next=replaceDay(current,change.date,change.replacements);const body={name:locationName};if(next.length)body.specialHours={specialHourPeriods:next};const url=apiBase+locationName+'?updateMask=specialHours';await request(url+'&validateOnly=true',{method:'PATCH',body:JSON.stringify(body)});await request(url,{method:'PATCH',body:JSON.stringify(body)});const verified=await read();periods=verified.specialHours?.specialHourPeriods||[];loadDay();if(signature(periods)!==signature(next))throw Error('保存後のデータが一致しません。登録内容を確認してください。');notice('Googleへの保存を確認しました。検索・マップへの表示には時間がかかる場合があります。','success');}catch(e){notice(e.message,'error');}finally{busy=false;controls();}}
$('origin').textContent=location.origin;try{$('client-id').value=localStorage.getItem(configKey)||'';}catch{}$('setup').open=!$('client-id').value;
const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const part=t=>parts.find(p=>p.type===t).value;$('date').value=`${part('year')}-${part('month')}-${part('day')}`;loadDay();
$('save-config').onclick=()=>{const id=$('client-id').value.trim();if(!/^[a-zA-Z0-9_-]+\.apps\.googleusercontent\.com$/.test(id)){notice('正しいOAuthクライアントIDを入力してください。','error');return;}try{localStorage.setItem(configKey,id);}catch{notice('端末に設定を保存できません。接続は可能ですが次回は再入力してください。','error');return;}$('setup').open=false;notice('接続設定を保存しました。「Googleに接続」を押してください。');};
$('connect').onclick=()=>{if(busy)return;const id=$('client-id').value.trim();if(!/^[a-zA-Z0-9_-]+\.apps\.googleusercontent\.com$/.test(id)){$('setup').open=true;$('client-id').focus();notice('初回の接続設定を行ってください。','error');return;}if(!window.google?.accounts?.oauth2){notice('Googleログインを読み込めません。通信状態やコンテンツブロッカーを確認して再読み込みしてください。','error');return;}busy=true;controls();const generation=++session;const client=google.accounts.oauth2.initTokenClient({client_id:id,scope:'https://www.googleapis.com/auth/business.manage',include_granted_scopes:false,error_callback:()=>{busy=false;controls();notice('ログインを完了できませんでした。もう一度接続してください。','error');},callback:async response=>{if(generation!==session)return;if(response.error||!response.access_token){busy=false;controls();notice('Googleへの接続が許可されませんでした。','error');return;}token=response.access_token;expiresAt=Date.now()+Number(response.expires_in)*1000;try{const loc=await discover();if(generation!==session)return;locationName=loc.name;$('connection').textContent='接続済み';busy=false;await refresh();}catch(e){reset();notice(e.message,'error');}finally{busy=false;controls();}}});try{client.requestAccessToken({prompt:'select_account'});}catch(e){busy=false;controls();notice('Googleログインを開始できませんでした。再読み込みしてください。','error');}};
$('disconnect').onclick=()=>{const old=token;reset();if(old&&window.google?.accounts?.oauth2)google.accounts.oauth2.revoke(old,()=>{});notice('Googleとの接続を解除しました。');};
$('date').onchange=loadDay;$('open-day').onclick=()=>mode(false);$('closed-day').onclick=()=>mode(true);$('add-interval').onclick=()=>addRow();$('refresh').onclick=refresh;$('save').onclick=()=>confirmChange(false);$('delete').onclick=()=>confirmChange(true);$('cancel-confirm').onclick=()=>{$('confirm-dialog').close();pending=null;};$('confirm-dialog').addEventListener('cancel',()=>{pending=null;});$('apply-confirm').onclick=apply;

// Agent navigation uses the same selected date and editor as the visible UI.
if(document.modelContext?.registerTool){
  const lifecycle=new AbortController();
  const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'select_special_hours_date',title:'営業時間の日付を選択',description:'編集する日付を選び、その日の現在の特別営業時間を表示する。Googleへの保存は行わない。',inputSchema:{type:'object',properties:{date:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(busy||$('confirm-dialog').open)throw Error('処理中です。');parseDate(input?.date);$('date').value=input.date;loadDay();return {date:input.date,loaded,periods:rowsForDay()};}});
  register({name:'read_special_hours',title:'特別営業時間を確認',description:'接続済みのGoogleから読み込んだ特別営業時間を返す。再読み込みや保存は行わない。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){if(!loaded)throw Error('Googleに接続し、営業時間を読み込んでください。');return {selectedDate:$('date').value,periods:structuredClone(periods)};}});
  window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
