export function dateKey(d){return `${d.year}-${String(d.month).padStart(2,'0')}-${String(d.day).padStart(2,'0')}`;}
export function parseDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw Error('日付を選んでください。');const [year,month,day]=s.split('-').map(Number);const d=new Date(Date.UTC(year,month-1,day));if(year<2000||year>9999||d.getUTCFullYear()!==year||d.getUTCMonth()+1!==month||d.getUTCDate()!==day)throw Error('有効な日付を選んでください。');return {year,month,day};}
export function nextDate(s){const d=parseDate(s);const t=new Date(Date.UTC(d.year,d.month-1,d.day+1));return {year:t.getUTCFullYear(),month:t.getUTCMonth()+1,day:t.getUTCDate()};}
export function timeValue(t){return (t?.hours||0)*60+(t?.minutes||0);}
export function clock(t){const h=t?.hours||0;return `${h===24?'12':String(h%12||12)}:${String(t?.minutes||0).padStart(2,'0')} ${h>=12&&h<24?'pm':'am'}`;}
function epoch(d,t){return Date.UTC(d.year,d.month-1,d.day)+timeValue(t)*60000;}
export function signature(periods){return JSON.stringify(periods.map(p=>[dateKey(p.startDate),p.endDate?dateKey(p.endDate):dateKey(p.startDate),!!p.closed,p.closed?0:timeValue(p.openTime),p.closed?0:timeValue(p.closeTime)]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))));}
export function makePeriods(date,closed,rows){const startDate=parseDate(date);if(closed)return [{startDate,endDate:startDate,closed:true}];if(!rows.length)throw Error('営業時間を1つ以上指定してください。');return rows.map(r=>{for(const t of [r.openTime,r.closeTime]){if(!Number.isInteger(t.hours)||t.hours<0||t.hours>23||![0,30].includes(t.minutes))throw Error('時刻の分は00または30を選んでください。');}const endDate=r.nextDay?nextDate(date):startDate;const duration=epoch(endDate,r.closeTime)-epoch(startDate,r.openTime);if(duration<=0||duration>=86400000)throw Error('終了は開始より後、営業時間は24時間未満にしてください。');if(r.nextDay&&timeValue(r.closeTime)>=720)throw Error('翌日の終了時刻は午前11:30までにしてください。');return {startDate,endDate,openTime:r.openTime,closeTime:r.closeTime,closed:false};});}
export function replaceDay(existing,date,replacements){parseDate(date);const result=[...existing.filter(p=>dateKey(p.startDate)!==date),...replacements];for(let i=0;i<result.length;i++){const a=result[i];for(let j=i+1;j<result.length;j++){const b=result[j];if(dateKey(a.startDate)!==date&&dateKey(b.startDate)!==date)continue;const as=epoch(a.startDate,a.closed?{hours:0}:a.openTime),ae=a.closed?as+86400000:epoch(a.endDate||a.startDate,a.closeTime);const bs=epoch(b.startDate,b.closed?{hours:0}:b.openTime),be=b.closed?bs+86400000:epoch(b.endDate||b.startDate,b.closeTime);if(as<be&&bs<ae)throw Error('営業時間が重複しています。隣の日の営業時間も確認してください。');}}return result.sort((a,b)=>dateKey(a.startDate).localeCompare(dateKey(b.startDate))||timeValue(a.openTime)-timeValue(b.openTime));}
export function describe(p){return p.closed?'休業':`${clock(p.openTime)} – ${p.endDate&&dateKey(p.endDate)!==dateKey(p.startDate)?'翌日 ':''}${clock(p.closeTime)}`;}
export function weeklyClosedDays(periods){
  if(!Array.isArray(periods)||!periods.length)return null;
  const days=['SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'],open=new Set();
  for(const p of periods){const a=days.indexOf(p.openDay),b=days.indexOf(p.closeDay);if(a<0||b<0)return null;const start=a*1440+timeValue(p.openTime);let end=b*1440+timeValue(p.closeTime);if(end<=start)end+=10080;for(let day=Math.floor(start/1440);day*1440<end;day++)open.add(day%7);}
  return days.filter((_,index)=>!open.has(index));
}
